services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "mkdocs"
    volumes:
      - "/opt/mkdocs/docs:/docs"
      - "/opt/mkdocs/mkdocs.yml:/mkdocs.yml"
    ports:
      - "80:8000"
