name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - test/action
    tags:
      - '*'

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: print working dir
        run: |
          echo $(pwd)
          echo $(ls)

      - name: install mkdocs and mike
        run: |
          pip install mkdocs-material mike mkdocs-macros-plugin mkdocs-glightbox
      
      - name: determine version
        id: version
        run: |
          if [["${{ github.ref }}" == refs/tags/v*]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          else
            VERSION=$(mike list --config-file /mkdocs.yml | grep '\[latest\]' | awk '{print $1}')
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: echo latest version
        run: |
          echo $(mike list --config-file /mkdocs.yml | grep '\[latest\]' | awk '{print $1}')

      - name: deploy docs
        run: |
          if [[ "${{ env.IS_VERSION }}" == "true"]]; then
          mike deploy --push --config-file ../mkdocs.yml --update-aliases ${{  env.VERSION  }} latest
          fi